### ISSUE TITLE
Implement legacy bouncer protocol

### ISSUE THREAD

**Issue by hellais** [ooni/orchestra#31]
We should implement the legacy bouncer protocol so we can discontinue the ooni-backend based bouncer.

This is the specification: https://github.com/TheTorProject/ooni-spec/blob/master/oonib.md#40-bouncer, but it should be double checked with the actual implementation to be sure they are indeed aligned.

**Comment by bassosimone** [comment]
This has been implemented at https://github.com/ooni/backend/issues/437.
