### ISSUE TITLE
Add support for giving out endpoints to test with tcp_connect

### ISSUE THREAD

**Issue by hellais** [ooni/orchestra#51]
In the pre 3.0 OONI Probe we would sync stuff from `ooni-resources` and in particular use what is inside of https://github.com/OpenObservatory/ooni-resources/tree/master/bridge_reachability for testing the reachability of bridges.

In 3.0 we don't do this anymore (and we actually don't even download the full test-lists, but rather fetch a subset at runtime).

We should add an endpoint in orchestrate (similar to the `urls` endpoints: https://github.com/ooni/orchestra/blob/master/orchestrate/orchestrate/api/v1/api.go#L32) for TCP endpoints.

**Comment by Em4E** [comment]
My use case for this is I want to test for blocking of the big public DNS servers that also support encryption, like dns.google.com, 1.1.1.1, and 9.9.9.9. I can have port 443 (DNS over HTTPS) tested by adding them to citizenlab/test-lists as ordinary URLs (https://github.com/citizenlab/test-lists/pull/405). But I'd also like to test ports 53 (ordinary DNS) and 853 (DNS over TLS) with a tcp_connect test.

**Comment by grote** [comment]
The orchestra serves data to probes from a postgresql database. The database needs to be filled with a script similar to [/scripts/sync-test-lists.py](https://github.com/ooni/orchestra/blob/master/scripts/sync-test-lists.py).

For a first iteration the filling script can use this URL:

    https://github.com/OpenObservatory/ooni-resources/blob/master/bridge_reachability/tor-bridges-ip-port.csv

Later, this might be changed to a dedicated repo as the current one is still powering legacy probes.

For now, the postgres table can mirror the structure of that CSV.

**Comment by hellais** [comment]
This is related to: https://github.com/ooni/orchestra/issues/68

**Comment by bassosimone** [comment]
We decided to write a different kind of test, focusing on Tor (https://github.com/ooni/probe-engine/issues/226), which prompted me to create another issue for giving out the configuration for such test (https://github.com/ooni/orchestra/issues/82). I did this because I didn't want to significantly change the scope of this issue, which AFAICT was also focusing on non Tor targets.

I am also removing this issue from the cycle backlog, since we should work on #82 instead.

**Comment by hellais** [comment]
We have ended up doing a different strategy for testing tor bridge and directory authority targets.

The targets are now checked into this code repository: https://github.com/ooni/sysadmin/blob/master/ansible/roles/probe-services/templates/tor_targets.json.

I am going to close this issue as done, since the original goal was of testing tor targets.

I think that if we would like to also test non-tor targets we should open a dedicated issue about that, but starting from the test specification itself (in probe-engine).
