### ISSUE TITLE
Add support for giving out psiphon configs

### ISSUE THREAD

**Issue by hellais** [ooni/orchestra#78]
We discussed with @bassosimone @FedericoCeratto implementing this inside of https://github.com/ooni/orchestra/blob/master/orchestrate/orchestrate/api/v1/api.go#L30 protected with authentication to prevent leaking of the these secrets.

Things that we still have to figure out are:
* How to detect that a certain sponsorID has been compromised or abused
* What to do to rotate the secrets possibly setting up some API with the psiphon dev team

Related: https://github.com/ooni/orchestra/issues/68

**Comment by bassosimone** [comment]
@hellais, with respect of what you said above:

> Things that we still have to figure out are:
> * How to detect that a certain sponsorID has been compromised or abused
> * What to do to rotate the secrets possibly setting up some API with the psiphon dev team

I have discussed these matters on a private channel with @rod-hynes and we concluded that "static values may be fine for the foreseeable future, based on operational experience".

IOW, I believe we can green light this task and implement the API.
